<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE school [
<!ELEMENT school (student)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT student (phone|email|lastname|firstname)*>
<!ATTLIST student
    id ID #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT firstname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT lastname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT email (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT phone (#PCDATA)>
]>
<school>  
 <student id="s1">  
  <firstname>ankush</firstname>  
  <lastname>thakur</lastname>  
  <email>beingjavaguy.gmail.com</email>  
  <phone>7678767656</phone>  
 </student>  
 <student id="s2">  
  <firstname>aarti</firstname>  
  <lastname>gupta</lastname>  
  <email>aartigupta.gmail.com</email>  
  <phone>9876546545</phone>  
 </student>  
</school>  
